cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<juguete_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<juguete_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

happytoys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('inicio.urls')),
    path('cart/', include('cart.urls')),
] +  static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

inicio/urls.py
from django.conf.urls import url, include
from inicio.views import *

app_name = 'inicio'


urlpatterns = [
    url(r"^$",inicio),
    url(r'^descripcion/$',descripcion),
    url(r'^login/$',login),
    url(r'^login/logueado/$',vista_logueado),
    url(r'^juguetes/$',juguetes,name='juguetes'),
    url(r'^buscador/$',buscador),
    url(r'^logout/$',logout,name ='logout'),
    url(r'^juguetes/(?P<juguete_id>\d+)/$', juguete_detail,name='jugueteDetail'),
    url(r'^juguetes/agregar/$',newJuguete,name='newJuguete'),
    url(r'^juguetes/new/$',newToy,name='newToy'),
    url(r'^images/$',showImage,name='showImage'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddJugueteForm(forms.Form):
    cantidad = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from inicio.models import Juguete
from .cart import Cart
from .forms import CartAddJugueteForm


@require_POST
def cart_add(request, juguete_id):
    
    cart = Cart(request)
    juguete = get_object_or_404(Juguete, id=juguete_id)
    form = CartAddJugueteForm(request.POST)
    if form.is_valid():
        print("se entra")
        cd = form.cleaned_data
        cart.add(juguete=juguete, cantidad=cd['cantidad'], update_cantidad=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, juguete_id):
    cart = Cart(request)
    juguete = get_object_or_404(Juguete, id=juguete_id)
    cart.remove(juguete)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_cantidad_form'] = CartAddJugueteForm(initial={'cantidad': item['cantidad'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'plantilla.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block contenido %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Tu carrito de compra
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        Mi orden de compra:
                        <a href="{% url "cart:cart_detail" %}" style="color: black">
                            {{ totail_items }} juguetes {{ totail_items|pluralize }}, $ {{ cart.get_total_precio }}
                        </a>
                        {% else %}
                        Tu carrito esta vacio.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Imagen</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Eliminar</th>
                        <th>Precio unitario</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with juguete=item.juguete  %}
                        <tr>
                            <td>
                                <a href="{{ juguete.get__absolute_url }}">
                                    <img src="{{ MEDIA_URL }}{{ juguete.imageFile }}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ juguete.nombre }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" juguete.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_cantidad_form.cantidad }}
                                    {{ item.update_cantidad_form.update }}
                                    <input type="submit" value="Actualizar" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" juguete.id %}">Eliminar</a>
                            </td>
                            <td>$ {{ item.precio }}</td>
                            <td>$ {{ item.total_precio }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>$ {{ cart.get_total_precio }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "inicio:juguetes" %}" class="btn btn-default">Continuar comprando</a>
            <a href="" class="btn btn-primary">Pagar</a>
        </p>
        </div>
    </div>
{% endblock %}