cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<juguete_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<juguete_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

happytoys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('inicio.urls')),
    path('cart/', include('cart.urls')),
] +  static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

inicio/urls.py
from django.conf.urls import url, include
from inicio.views import *

app_name = 'inicio'


urlpatterns = [
    url(r"^$",inicio),
    url(r'^descripcion/$',descripcion),
    url(r'^login/$',login),
    url(r'^login/logueado/$',vista_logueado),
    url(r'^juguetes/$',juguetes,name='juguetes'),
    url(r'^buscador/$',buscador),
    url(r'^logout/$',logout,name ='logout'),
    url(r'^juguetes/(?P<juguete_id>\d+)/$', juguete_detail,name='jugueteDetail'),
    url(r'^juguetes/agregar/$',newJuguete,name='newJuguete'),
    url(r'^juguetes/new/$',newToy,name='newToy'),
    url(r'^images/$',showImage,name='showImage'),
]

inicio/models.py
from django.db import models

# Create your models here.

class Juguete(models.Model):
    nombre      = models.CharField(max_length = 100,blank = False, null = False,verbose_name = "Nombre juguete")
    precio      = models.IntegerField(blank = True,null = True,verbose_name = "Precio juguete")
    cantidad    = models.IntegerField(blank = True,null = True,verbose_name = "Cantidad juguete")
    descripcion = models.CharField(max_length = 500,blank = True, null =  True,verbose_name = "Descripcion")
    imageFile   = models.FileField(upload_to='images/',blank = True, null = True, verbose_name= "Imagen")    
    
    
    def __str__(self):
        return u'%s' %(self.nombre)
    

class Boleta(models.Model):
    fecha = models.DateTimeField(blank = False, null = False, auto_now_add = True,verbose_name = "Fecha boleta")
    total = models.IntegerField(blank = False, null = False,verbose_name = "Total boleta")
    juguete = models.ForeignKey(Juguete,on_delete=models.CASCADE,blank = False,null = True)
    def __str__(self):
        return u'%s' %(self.fecha)

class Image(models.Model):
    name = models.CharField(max_length=500)
    imageFile = models.FileField(upload_to='images/', null = True, verbose_name= "")
    
    def __str__(self):
        return self.name + ": " + str(self.imageFile)
    

inicio/forms.py
from django import forms
from .models import *

class JugueteForm(forms.ModelForm):
    
    class Meta:
        model = Juguete
        fields = ("nombre","precio","cantidad","descripcion","imageFile")
    def __init__(self,*args,**kwargs):
        super(JugueteForm,self).__init__(*args,**kwargs)
        self.fields["nombre"].widget.attrs.update({'class':'form-control','placeholder':'Ingrese nombre juguete'})
        self.fields["precio"].widget.attrs.update({'class':'form-control','placeholder':'Ingrese precio'})
        self.fields["cantidad"].widget.attrs.update({'class':'form-control','placeholder':'Ingrese cantidad'})
        self.fields["descripcion"].widget.attrs.update({'class':'form-control','placeholder':'Ingrese alguna descripción'})
        self.fields["imageFile"].widget.attrs.update({'class': 'form-control-file'})


class ImageForm(forms.ModelForm):
    class Meta:
        model= Image
        fields= ("name", "imageFile")

inicio/views.py
from django.shortcuts import render, redirect
import time
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from cart.forms import CartAddJugueteForm
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

def inicio(request):
    print (request.user.username)
    context  = {"usuario" : "Andres Calfulef","fecha": time.strftime("%d/%m/%y")}
    return render(request,"inicio.html",context)

def descripcion(request):
    print (request.user.username)
    return render(request,"descripcion.html")

def buscador(request):
    context = {}
    if request.method == "POST":    
        if "search" in request.POST.keys():
            resultado = Juguete.objects.filter(nombre__contains = request.POST['search'])
            context = {'resultado':resultado}
    return render(request,"buscador.html",context)

def juguetes(request):
    context = {}
    if request.method == "POST":
        if "buscador" in request.POST.keys():
            resultado = Juguete.objects.filter(nombre__contains = request.POST['buscador'])
            context = {'resultado': resultado}
    
    else: # si ingremos a la URL y no realizamos ninguna busqueda
        resultado = Juguete.objects.all()
        context = {'resultado': resultado}

    return render(request,"juguetes.html",context)

def juguete_detail(request,juguete_id):
    juguete = get_object_or_404(Juguete, id=juguete_id)
    cart_juguete_form = CartAddJugueteForm()
    context = {
        'juguete': juguete,
        'cart_juguete_form': cart_juguete_form
    }
    return render(request, 'detail.html', context)



def login(request):
    if request.method == "POST":
        if ("user" in request.POST.keys()) and ("password" in request.POST.keys()):
            user = auth.authenticate(username = request.POST['user'] , password = request.POST['password'])
            print(request.POST['user'])
            print(user)
            if user is not None and user.is_active:
                auth.login(request,user)
                return redirect("/")
            else:
                contexto = {"error" : "error"}
                return render(request,"login.html",contexto)

        else:
            contexto = {"error" : "error"}
            return render(request,"login.html",contexto)
    return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect("/")

@login_required(login_url='/login')
def vista_logueado(request):
    if request.method == 'POST':
        if ("cerrar" in request.POST.keys()):
            auth.logout(request)
            return redirect("/")
    return render(request,"logueado.html")

def newJuguete(request):
    if request.method == "POST":
        form = JugueteForm(request.POST or None)
        if form.is_valid():
            form.save()
        if ("nombre" in request.POST.keys()) and ("precio" in request.POST.keys()) and ("cantidad" in request.POST.keys()) and ("descripcion" in request.POST.keys()):
            juguete=Juguete()
            juguete.nombre=request.POST["nombre"]
            juguete.precio=request.POST["precio"]
            juguete.cantidad=request.POST["cantidad"]
            juguete.descripcion=request.POST["descripcion"]
            juguete.save()
        if ("cerrar" in request.POST.keys()):
            auth.logout(request)
            return redirect("/login/")
    form = JugueteForm(request.POST or None)
    contexto = {"usuario":request.user,"form":form}
    return render(request,"newJuguete.html",contexto)

def newToy(request):
    if request.method == "POST":
        form = JugueteForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
        if ("nombre" in request.POST.keys()) and ("precio" in request.POST.keys()) and ("cantidad" in request.POST.keys()) and ("descripcion" in request.POST.keys()  and ("imageFile" in request.POST.keys())):
            juguete=Juguete()
            juguete.nombre      =request.POST["nombre"]
            juguete.precio      =request.POST["precio"]
            juguete.cantidad    =request.POST["cantidad"]
            juguete.descripcion =request.POST["descripcion"]
            juguete.imageFile   =request.POST["imageFile"]
            juguete.save()
    else:
        form = JugueteForm(request.POST or None)
    contexto = {"usuario":request.user,"form":form}
    return render(request,"newToy.html",contexto)



def showImage(request):
    lastImage = Image.objects.last()
    print(lastImage)
    imageFile = lastImage.imageFile
    print(imageFile)
    form = ImageForm(request.POST or None, request.FILES or None)
  
    contexto = {"usuario":request.user,"form":form}
    return render(request,"newJuguete.html",contexto)
    
    context = {'imageFile': imageFile,
               'form': form}
    
    return render(request,'images.html',context)

templates/buscador.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Buscador de juguetes</title>
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
</head>
<body style="background-color: #eaeaea">
    <form class="form-inline my-2 my-lg-0" method = "POST" >
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="text" placeholder="Search" name = "search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
            </tr>
        </thead>
        <tbody>
            <tr class="table-primary">
                {%for i in resultado%}
                <tr>
                    <td>{{i.nombre}}</td>
                    <td>{{i.precio}}</td>
                </tr>
                {% endfor%}
            </tr>
        </tbody>
    </table>

</body>
</html>

templates/descripcion.html
{% extends 'inicio.html' %}
{% block contenido %}

<div class="jumbotron ">
	<h1 class="display-4">HappyToys</h1>
	<p class="lead">El proyecto consistira en una pagina web donde se puedan comprar juguetes, se espera poder realizar lo siguiente:</p>
	<hr class="my-4">
	
	<div class="container">
		<div class= "row">
		<div class="col-sm">
			<img src="/media/forky.jpg" class="img-fluid"  alt="juguete">
		</div>
	
		<div class="col-sm">
			<ul class="list-group">
				<li class="list-group-item d-flex justify-content-between align-items-center">
				Carrito de compra
				<span class="badge badge-primary badge-pill">1</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Utilizar microservicios(no oficial)
					<span class="badge badge-primary badge-pill">2</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Aprender Mucho!
					<span class="badge badge-primary badge-pill">3</span>
				</li>
			</ul>
		</div>
	</div>
	
	</div>
	

  	
  
  
</div>

	
{% endblock contenido %}

templates/detail.html
{% extends 'plantilla.html' %}
{% load static %}
{% block contenido %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{{ MEDIA_URL }}{{ juguete.imageFile }}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ juguete.nombre }}</h3>
                            <h6>{{ juguete.descripcion }}</h6>
                            <p class="text-muted">$ {{ juguete.precio }}</p>
                            <form action="{% url "cart:cart_add" juguete.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_juguete_form }}
                                <input type="submit" value="Agregar al carrito" class="btn btn-primary">
                            </form>
                            <p>{{ juguete.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

templates/images.html
<html>
<head>
<meta charset="UTF-8">
<title>Upload Images</title>
</head>
<body>

<h1>Image Uploader</h1>
<form enctype="multipart/form-data" method="POST" action="">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Upload"/>
</form>

<br><br>
<img src='{{ MEDIA_URL }}{{ imageFile }}'>
<br><br>
</p>

</body>
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script><script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>

templates/inicio.html
{% extends 'plantilla.html' %}
{% block contenido %}

	
    <div class="container">
      <div class="row">
        <div class="col-sm-1-12">
        {% if user.is_authenticated %}
          <h3>
            Bienvenido 
            <small class="text-muted">{{user.username}}</small>
          </h3>
        {% endif %}
        
        </div>
      </div>

      <div class="row">
        <div class="col-xs-1-12">
          <h2 style="color:#428bca" > hoy es {{fecha}} <h1>
        </div>
        <div class="col-xs-1-12">
          <img src='media/imagen.jpg'>
        </div>
      </div>
    </div>
  
 


	
{% endblock contenido %}

templates/juguetes.html
{% extends 'plantilla.html' %}
{% load static %}
{% block contenido %}
    
    <br>
    <form class="form-inline my-2 my-lg-0" method = "POST" >
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="text" placeholder="Buscar un juguete" name = "buscador">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
    </form>
    <br><br>


    <div class="card-columns">
        {% for juguete in resultado %}
            <div class="card bg-secondary"  >
                <div class="card-body text-center" >
                    <a href= "{% url 'inicio:jugueteDetail' juguete.id %}">
                        <img src="{{ MEDIA_URL }}{{ juguete.imageFile }}" class="card-img-top"  alt="...">
                    </a>
                    <h5 class="card-title">{{juguete.nombre}}</h5>
                    <p class="card-text">{{juguete.descripcion}}</p>
                </div>
                <div class="card-footer text-center">
                    <h5 class="text-muted">${{juguete.precio}}</h5>
                    
                </div>
            </div>
        {% endfor %}
       
    </div>


{% endblock contenido %}

templates/login.html
{% extends 'plantilla.html' %}
{% block contenido %}
<div class="container">
    <div class="row">
    <form method="POST">
        <fieldset>
            <legend>Ingreso de usuario</legend>
        
            <div class="form-group">
            <label for="exampleInputEmail1">Usuario</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese usuario" name="user">
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
            </div>
            
            
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>
    </div>
</div>

{% endblock contenido %}

templates/logueado.html
{% extends 'plantilla.html' %}
{% block contenido %}
<p> Logueado exitoso! </p>

<form method="POST" role="form" action=".">
    {% csrf_token %}
    <input type="hidden" value="logout" name="cerrar">
    <button class="btn btn-info  text-uppercase waves-effect waves-light" type="submit">Cerrar la sesión</button>
</form>
{% endblock %}

templates/nav_bar.html
{% extends 'plantilla.html' %}
{% block contenido %}
	

{% endblock contenido %}

templates/newJuguete.html
{% extends 'plantilla.html' %}
{% block contenido %}

<div class="container">
    <form class="juguete" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">Crear</button>
    <form>
</div>


{% endblock %}

templates/newToy.html
{% extends 'plantilla.html' %}
{% block contenido %}

<div class="container">
    <form enctype="multipart/form-data" class="juguete" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">Crear</button>
    <form>
</div>


{% endblock %}

templates/plantilla.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Taller de Proyectos Web</title>
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
</head>
<body style="background-color: #fff">
	

	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">HappyToys</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/descripcion">Descripcion del proyecto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/juguetes">Nuestros juguetes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inicio:newToy' %}">Agregar nuevos juguetes</a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    Hola {{user.username}} 
    <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'inicio:logout' %}">Cerrar sesion</a>
     
    {% else %}
      <a class="btn btn-secondary my-2 my-sm-0" href="/login">Iniciar sesion</a>
    {% endif %}

    
    


  </div>
</nav>


  {% block contenido %}
 
	
	{% endblock contenido %}
	


</body>
</html>